export default {
  HTML_ELEMENTS_IDS: {
    place_window: "place",
    place_container: "place-container",
    place_viewer: "place-viewer",
    place_camera: "place-camera",
    place_canvas: "place-canvasse",
    cursor_position_container: "place-coordinates",
    color_selector_open_container: "color-selector-container__open_actions",
    open_container_btn: "color-selector-container__open-actions__open-btn",
    color_selector_container: "color-selector-container",
    colors_container: "color-selector-container__colors",
    colors_actions_container: "color-selector-container__actions",
    colors_container_close: "color-selector-container__actions__close",
  },
  CANVAS: {
    DEFAULT_COLORS_PALLET: [
      "#6d001a",
      "#be0039",
      "#ff4500",
      "#ffa800",
      "#ffd635",
      "#fff8b8",
      "#00a368",
      "#00cc78",
      "#7eed56",
      "#00756f",
      "#009eaa",
      "#00ccc0",
      "#2450a4",
      "#3690ea",
      "#51e9f4",
      "#493ac1",
      "#6a5cff",
      "#94b3ff",
      "#811e9f",
      "#b44ac0",
      "#e4abff",
      "#de107f",
      "#ff3881",
      "#ff99aa",
      "#6d482f",
      "#9c6926",
      "#ffb470",
      "#000000",
      "#515252",
      "#898d90",
      "#d4d7d9",
      "#ffffff",
    ],
    MAX_ZOOM: 40,
    MIN_ZOOM: 0.2,
    HEIGHT: 1000,
    WIDTH: 1000,
  },
};
